# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18szW249yZAUz8xCYkqhHoWLn0uwZEKCc
"""

import lightkurve as lk
import numpy as np
import matplotlib.pyplot as plt
from astropy.timeseries import BoxLeastSquares
import warnings

warnings.filterwarnings("ignore", category=RuntimeWarning)

print("🔄 Starting Exoplanet Detection...")

# -----------------------------
# 1. DOWNLOAD LIGHT CURVE DATA
# -----------------------------
target = "Kepler-10"
print("📡 Searching for data...")

search_result = lk.search_lightcurve(target, mission="Kepler")

print("⬇️ Downloading light curve...")
lc = search_result.download()

# Clean data
print("🧹 Cleaning data...")
lc = lc.remove_nans().remove_outliers(sigma=5).normalize()

# -----------------------------
# 2. DETREND LIGHT CURVE
# -----------------------------
print("📉 Flattening light curve...")
flattened_lc = lc.flatten(window_length=301)

time = flattened_lc.time.value
flux = flattened_lc.flux.value

mask = np.isfinite(time) & np.isfinite(flux)
time = time[mask]
flux = flux[mask]

# -----------------------------
# 3. BLS TRANSIT DETECTION
# -----------------------------
print("🔍 Running BLS transit search...")

periods = np.linspace(0.5, 5, 5000)

bls = BoxLeastSquares(time, flux)
results = bls.power(periods, 0.1)

best_period = results.period[np.argmax(results.power)]

print(f"✅ Detected Orbital Period: {best_period:.4f} days")

# -----------------------------
# 4. PLOT
# -----------------------------
plt.figure(figsize=(10,5))
plt.plot(results.period, results.power)
plt.xlabel("Period (days)")
plt.ylabel("BLS Power")
plt.title("BLS Periodogram")
plt.show()

# -----------------------------
# 5. PHASE FOLDING
# -----------------------------
print("📊 Generating phase-folded plot...")

folded = flattened_lc.fold(period=best_period)
folded.plot(title=f"Phase Folded Light Curve (Period = {best_period:.3f} days)")
plt.show()

# -----------------------------
# 6. TIDAL LOCKING
# -----------------------------
def tidal_locking_likelihood(period_days):
    if period_days < 2:
        return "Almost certainly tidally locked"
    elif period_days < 10:
        return "Very likely tidally locked"
    elif period_days < 20:
        return "Possibly tidally locked"
    else:
        return "Unlikely tidally locked"

print(f"🌍 Tidal Locking Assessment: {tidal_locking_likelihood(best_period)}")

print("🎉 Done!")